/**
 * Build script: bundle src/client.js plus CodeMirror / xterm into client/entry.mjs
 * (the plugin static server only exposes the client/ subtree, so the output must
 * be self-contained with no bare imports).
 *
 * xterm CSS is inlined as text into the bundle (injected as <style> on mount).
 * Usage: npm install && npm run build
 */
import { build } from "esbuild";

await build({
	entryPoints: ["src/client.js"],
	bundle: true,
	format: "esm",
	outfile: "client/entry.mjs",
	target: "es2022",
	charset: "utf8",
	minify: false, // keep checked-in output readable; set true to shrink
	loader: { ".css": "text" }, // import "@xterm/xterm/css/xterm.css" → string
	banner: { js: "/* vscode-editor client bundle — generated by npm run build; source is src/client.js */" },
});
console.log("built → client/entry.mjs");
