/**
 * Build script: bundle src/client.js into a self-contained client/entry.mjs
 * (the plugin static server only exposes the client/ subtree, so the output
 * must have no bare imports).
 *
 * The client has zero third-party deps (vanilla JS); esbuild only bundles.
 * Usage: npm install && npm run build
 */
import { build } from "esbuild";

await build({
	entryPoints: ["src/client.js"],
	bundle: true,
	format: "esm",
	outfile: "client/entry.mjs",
	target: "es2022",
	charset: "utf8",
	minify: false,
	banner: { js: "/* db-client client bundle — generated by npm run build; source is src/client.js */" },
});
console.log("built → client/entry.mjs");
